### ISSUE TITLE
unmute video on hover

### ISSUE THREAD

**Issue by maraheem** [biohzrdmx/jQuery.hoverPlay#1]
Have used your plugin in our website and on hover I am trying to play videosVideos are playing only when "muted" option is added but without sound, and if "muted" option is not added then I am getting below errors:
Firefox error:
_NotAllowedError: The play method is not allowed by the user agent or the platform in the current context, possibly because the user denied permission._
Chrome error:
_Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first._

Is there a way to unmute the video on hover when video starts playing. Any help would be appreciated
Thanks,

**Comment by biohzrdmx** [comment]
Hi Raheem, it seems that this is about the media autoplay policy, which doesn't allow videos with sound to be played automatically (that is, without the user interacting first by clicking on it).

Here's a link to the policy update for Chrome: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes (a similiar policy is in place for Firefox)

There may be a workaround, but as the policy is in place to improve user experience I currently have no plans on implementing such workaround, but you are free to do so if you like.

Regards!

**Comment by maraheem** [comment]
Thanks for your reply, will see for any other workaround.
